name: Deno CI
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} test
    runs-on: ${{ matrix.os }}-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      matrix:
        os: [macOS, ubuntu, windows]
    env:
      GH_ACTIONS: true
      DENO_BUILD_MODE: release
      V8_BINARY: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Run tests
        run: deno test
      - name: Check formatting
        run: deno fmt --check
        if: ${{ !contains(matrix.os, 'windows') }}
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Publish package
        run: deno publish